### ISSUE TITLE
Unusable with non-default match path

### ISSUE THREAD

**Issue by miketlk** [thruthesky/path-mapper#1]
Unfortunately, due to a hard-coded path in **provideTerminalLinks()** function, the extension does not map the non-default path correctly. Currently, it works only when terminal links begin with '/docker/sonub-backend' independently of configuration.

The issue is caused by the code line below:

https://github.com/thruthesky/path-mapper/blob/a6dd13feae76d706d81746f58084353cdddcd81b/src/extension.ts#L30

**Comment by thruthesky** [comment]
I will look into it :)

**Comment by miketlk** [comment]
Hi @thruthesky , do you have any progress fixing this issue?
Sadly, because of that, your smartly designed plugin can't be used outside the default settings for paths.

**Comment by andjo** [comment]
Meanwhile I think the extension should be unpublished from the marketplace. It makes no sense to keep there in the current state.

**Comment by thruthesky** [comment]
Sorry for keeping it long.
It should work as expected with version 0.0.7 and later.
