### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by sergju** [thruthesky/path-mapper#2]
This extension can be very usefull for me.
I've modified locally but would be good if some features are available from the repository.
1. Auto start on vscode start.
2. Several mappings
3. Set position after file is opened - by a line number if presented and by a column

**Comment by thruthesky** [comment]
Can you explain it again? So I can better understand what would be done better.

**Comment by superlevure** [comment]
For #2 I think the author means that it would be useful to support a list of mapping:

```
/foo -> /new_foo
/bar -> /new_bar
etc
```

+1 on this suggestion

**Comment by thruthesky** [comment]
> For #2 I think the author means that it would be useful to support a list of mapping:
> 
> ```
> /foo -> /new_foo
> /bar -> /new_bar
> etc
> ```
> 
> +1 on this suggestion

Sorry to keep everyone wait long. I will work on it immedately.

**Comment by superlevure** [comment]
Thanks @thruthesky! Just in case, the extension is not usable right now because of https://github.com/thruthesky/path-mapper/issues/1

**Comment by thruthesky** [comment]
- Auto start works now.
- several mapping works now.
- `Set position after file is opened - by a line number if presented and by a column` will be opened in a new issue.
